#pragma once
#define WM_BLUETOOTH_RECEIVED	(WM_APP + 0x100)
#define WM_BLUETOOTH_CONNECTED	(WM_APP + 0x101)
#define WM_BLUETOOTH_ERROR		(WM_APP + 0x102)
#define WM_BLUETOOTH_CLOSED		(WM_APP + 0x103)

#define WM_CLOSE_CAMERA_WINDOW	(WM_APP + 0x200)
#define WM_CAMERA_LIGHT_STATUS	(WM_APP + 0x201)
